version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-binary:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/project/node_modules
      # - run:
      #     name: Install Python 3
      #     command: |
      #       sudo apt-get install python3 python3-pip
      - run:
          name: Run Build
          command: |
            yarn run build
            which python
            python3 --version
            python --version
            alias python=python3
            python --version
            gcc --version
            g++ --version
            make --version
            # yarn start --node-range node18 --output dist
      - store_artifacts:
          path: dist
workflows:
  build:
    jobs:
      - build-binary